image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: foodev

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - python --version
