# Generated by Django 3.1 on 2020-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('OWNER', 'Owner')], default='REGULAR', max_length=10),
        ),
    ]
